[2024-05-30T15:25:35.230+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tipico_dag.load_data_to_redshift manual__2024-05-30T15:20:27.830190+00:00 [queued]>
[2024-05-30T15:25:35.237+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tipico_dag.load_data_to_redshift manual__2024-05-30T15:20:27.830190+00:00 [queued]>
[2024-05-30T15:25:35.238+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2024-05-30T15:25:35.249+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): load_data_to_redshift> on 2024-05-30 15:20:27.830190+00:00
[2024-05-30T15:25:35.263+0000] {standard_task_runner.py:60} INFO - Started process 14790 to run task
[2024-05-30T15:25:35.267+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tipico_dag', 'load_data_to_redshift', 'manual__2024-05-30T15:20:27.830190+00:00', '--job-id', '185', '--raw', '--subdir', 'DAGS_FOLDER/tipico_dag.py', '--cfg-path', '/tmp/tmpbwsue_b6']
[2024-05-30T15:25:35.268+0000] {standard_task_runner.py:88} INFO - Job 185: Subtask load_data_to_redshift
[2024-05-30T15:25:35.311+0000] {task_command.py:423} INFO - Running <TaskInstance: tipico_dag.load_data_to_redshift manual__2024-05-30T15:20:27.830190+00:00 [running]> on host a71bb5ce980f
[2024-05-30T15:25:35.381+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tipico_dag' AIRFLOW_CTX_TASK_ID='load_data_to_redshift' AIRFLOW_CTX_EXECUTION_DATE='2024-05-30T15:20:27.830190+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-30T15:20:27.830190+00:00'
[2024-05-30T15:25:35.419+0000] {logging_mixin.py:188} INFO -        id  ...                              sportCurrentGameState
0  816775  ...                                                NaN
1  814989  ...  {"updatedAt": "0", "netSportCurrentGameState":...
2  815803  ...  {"updatedAt": "0", "netSportCurrentGameState":...
3  815057  ...  {"updatedAt": "0", "netSportCurrentGameState":...
4  814942  ...  {"updatedAt": "0", "netSportCurrentGameState":...

[5 rows x 21 columns]
[2024-05-30T15:25:35.428+0000] {base.py:83} INFO - Using connection ID 'redshift_default' for task execution.
[2024-05-30T15:25:36.027+0000] {logging_mixin.py:188} INFO - {816775}
[2024-05-30T15:25:36.339+0000] {warnings.py:109} WARNING - /opt/***/dags/tipico_etl.py:39: UserWarning: DB-API extension cursor.connection used
  cursor.execute(sql)

[2024-05-30T15:25:36.341+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/tipico_etl.py", line 39, in load_data_to_redshift
    cursor.execute(sql)
  File "/home/airflow/.local/lib/python3.8/site-packages/redshift_connector/cursor.py", line 248, in execute
    raise e
  File "/home/airflow/.local/lib/python3.8/site-packages/redshift_connector/cursor.py", line 241, in execute
    self._c.execute(self, operation, args)
  File "/home/airflow/.local/lib/python3.8/site-packages/redshift_connector/core.py", line 1959, in execute
    self.handle_messages(cursor)
  File "/home/airflow/.local/lib/python3.8/site-packages/redshift_connector/core.py", line 2166, in handle_messages
    raise self.error
redshift_connector.error.ProgrammingError: {'S': 'ERROR', 'C': '22001', 'M': 'value too long for type character varying(10000)', 'F': '../src/pg/src/backend/utils/adt/varchar.c', 'L': '484', 'R': 'varchar'}
[2024-05-30T15:25:36.356+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=tipico_dag, task_id=load_data_to_redshift, execution_date=20240530T152027, start_date=20240530T152535, end_date=20240530T152536
[2024-05-30T15:25:36.379+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 185 for task load_data_to_redshift ({'S': 'ERROR', 'C': '22001', 'M': 'value too long for type character varying(10000)', 'F': '../src/pg/src/backend/utils/adt/varchar.c', 'L': '484', 'R': 'varchar'}; 14790)
[2024-05-30T15:25:36.404+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-05-30T15:25:36.429+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
